import type { TargetLevel, TargetRole } from "../types/entry-test.types";

export const entryTestRoles: Array<{ value: TargetRole }> = [
  { value: "FE" },
  { value: "BE" },
  { value: "QA_QC" },
  { value: "BA" },
  { value: "DEVOPS" },
  { value: "DATA" },
];

export const entryTestSkillsByRole: Record<TargetRole, string[]> = {
  FE: [
    "HTML_CSS",
    "JAVASCRIPT",
    "TYPESCRIPT",
    "REACT",
    "NEXT_JS",
    "VUE",
    "NUXT",
    "ANGULAR",
    "SVELTE",
    "SVELTEKIT",
    "SOLID_JS",
    "ASTRO",
    "REMIX",
    "TAILWIND_CSS",
    "SASS",
    "BOOTSTRAP",
    "MATERIAL_UI",
    "REDUX",
    "ZUSTAND",
    "GRAPHQL",
    "REST_API",
    "WEBPACK",
    "VITE",
    "JEST",
    "VITEST",
    "CYPRESS",
    "PLAYWRIGHT",
    "REACT_NATIVE",
    "FLUTTER",
    "PWA",
    "WEB_ACCESSIBILITY",
  ],
  BE: [
    "JAVA",
    "SPRING_BOOT",
    "KOTLIN",
    "JAVASCRIPT",
    "TYPESCRIPT",
    "NODE_JS",
    "NEST_JS",
    "EXPRESS_JS",
    "PYTHON",
    "DJANGO",
    "FLASK",
    "FASTAPI",
    "CSHARP",
    "DOTNET",
    "GO",
    "RUST",
    "PHP",
    "LARAVEL",
    "RUBY",
    "RUBY_ON_RAILS",
    "SCALA",
    "ELIXIR",
    "CPP",
    "SQL",
    "POSTGRESQL",
    "MYSQL",
    "MONGODB",
    "REDIS",
    "GRAPHQL",
    "REST_API",
    "GRPC",
    "KAFKA",
    "RABBITMQ",
    "MICROSERVICES",
  ],
  QA_QC: [
    "MANUAL_TESTING",
    "AUTOMATION_TESTING",
    "API_TESTING",
    "WEB_TESTING",
    "MOBILE_TESTING",
    "PERFORMANCE_TESTING",
    "SECURITY_TESTING",
    "SELENIUM",
    "PLAYWRIGHT",
    "CYPRESS",
    "APPIUM",
    "POSTMAN",
    "JMETER",
    "K6",
    "CUCUMBER",
    "ROBOT_FRAMEWORK",
    "REST_ASSURED",
    "PYTEST",
    "JEST",
    "VITEST",
    "JAVASCRIPT",
    "TYPESCRIPT",
    "PYTHON",
    "JAVA",
    "CSHARP",
    "SQL",
    "GIT",
    "CI_CD",
  ],
  BA: [
    "REQUIREMENT_ANALYSIS",
    "BUSINESS_PROCESS_ANALYSIS",
    "STAKEHOLDER_MANAGEMENT",
    "USER_STORIES",
    "USE_CASES",
    "UML",
    "BPMN",
    "ERD",
    "DATA_MODELING",
    "SQL",
    "AGILE",
    "SCRUM",
    "KANBAN",
    "JIRA",
    "CONFLUENCE",
    "FIGMA",
    "AXURE",
    "BALSAMIQ",
    "WIREFRAMING",
    "PROTOTYPING",
    "UAT",
    "API",
    "REST_API",
    "GRAPHQL",
    "POSTMAN",
    "EXCEL",
    "POWER_BI",
    "TABLEAU",
    "PRODUCT_MANAGEMENT",
  ],
  DEVOPS: [
    "LINUX",
    "BASH",
    "POWERSHELL",
    "PYTHON",
    "GO",
    "DOCKER",
    "KUBERNETES",
    "HELM",
    "TERRAFORM",
    "ANSIBLE",
    "AWS",
    "AZURE",
    "GCP",
    "JENKINS",
    "GITHUB_ACTIONS",
    "GITLAB_CI",
    "ARGO_CD",
    "PROMETHEUS",
    "GRAFANA",
    "ELK_STACK",
    "DATADOG",
    "NGINX",
    "APACHE",
    "VAULT",
    "CLOUDFLARE",
    "KAFKA",
    "RABBITMQ",
    "REDIS",
    "POSTGRESQL",
    "MYSQL",
    "MONGODB",
    "NETWORKING",
    "CLOUD_SECURITY",
    "SRE",
    "CI_CD",
  ],
  DATA: [
    "PYTHON",
    "R",
    "SQL",
    "EXCEL",
    "POWER_BI",
    "TABLEAU",
    "PANDAS",
    "NUMPY",
    "SCIPY",
    "SCIKIT_LEARN",
    "TENSORFLOW",
    "PYTORCH",
    "KERAS",
    "JUPYTER",
    "SPARK",
    "HADOOP",
    "KAFKA",
    "AIRFLOW",
    "DBT",
    "SNOWFLAKE",
    "BIGQUERY",
    "REDSHIFT",
    "DATABRICKS",
    "POSTGRESQL",
    "MONGODB",
    "ELASTICSEARCH",
    "MACHINE_LEARNING",
    "DEEP_LEARNING",
    "NLP",
    "COMPUTER_VISION",
    "DATA_ENGINEERING",
    "DATA_ANALYTICS",
    "STATISTICS",
    "ETL",
    "DATA_VISUALIZATION",
  ],
};

export const entryTestLevels: Array<{ value: TargetLevel }> = [
  { value: "INTERN" },
  { value: "FRESHER" },
  { value: "JUNIOR" },
];
