#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm generate-schema

if ! git diff --exit-code schema-from-be.d.ts; then
  echo "Schema is outdated! Please review the changes."
  exit 1
fi

pnpm lint-staged
